# Generated by Django 5.1.6 on 2025-02-25 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'city'], name='jobs_locati_country_32db43_idx')],
                'unique_together': {('country', 'city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('other', 'Other')], max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.location')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='jobs_jobpos_categor_24358e_idx'), models.Index(fields=['location'], name='jobs_jobpos_locatio_53917f_idx'), models.Index(fields=['category', 'job_type'], name='jobs_jobpos_categor_d02e41_idx'), models.Index(fields=['created_at'], name='jobs_jobpos_created_d079a9_idx')],
            },
        ),
    ]
