# Generated by Django 5.1.6 on 2025-03-01 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobposting',
            name='jobs_jobpos_locatio_53917f_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobposting',
            name='jobs_jobpos_categor_d02e41_idx',
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['employer'], name='jobs_jobpos_employe_a620fa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active'], name='jobs_jobpos_is_acti_6314b1_idx'),
        ),
    ]
